version: 0.2

phases:
  pre_build:
    commands:
      - echo Loging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=102888717683.dkr.ecr.eu-west-1.amazonaws.com/plv2-qual
      - IMAGE_TAG=$(echo `date +%s`)
      - echo $IMAGE_TAG
      - echo $CODEBUILD_BUILD_ARN
      - echo $CODEBUILD_SOURCE_VERSION
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*build/plv2qual:" >/dev/null; then
          BRANCHE="qual";
        fi
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*build/plv2prod" >/dev/null; then
          BRANCHE="prod";
        fi
        if expr "${$CODEBUILD_SOURCE_VERSION}" : "qual" >/dev/null; then
          BRANCHE="qual";
        fi
      - |
        if expr "${$CODEBUILD_SOURCE_VERSION}" : "prod" >/dev/null; then
          BRANCHE="prod";
        fi
      - echo $BRANCHE

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:pl-front-error-manager.$BRANCHE .
      - docker tag $REPOSITORY_URI:pl-front-error-manager.$BRANCHE $REPOSITORY_URI:pl-front-error-manager.$BRANCHE.$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:pl-front-error-manager.$BRANCHE
      - docker push $REPOSITORY_URI:pl-front-error-manager.$BRANCHE.$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"pl-front-error-manager","imageUri":"%s"}]' $REPOSITORY_URI:pl-front-error-manager.$BRANCHE.$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
